### Pandas

#### Pandas - Panel Data is a python library.

###### Importing the library

In [2]:
import pandas as pd

#### Loading the Dataset

In [3]:
df=pd.read_csv("salaries.csv")
df.head()

   Unnamed: 0      rank discipline yrs.since.phd  yrs.service   sex    salary
0         1.0      Prof          B            19         18.0  Male  139750.0
1         2.0      Prof          B            20         16.0  Male  173200.0
2         3.0  AsstProf          B             4          3.0  Male   79750.0
3         4.0      Prof          B            45         39.0  Male  115000.0
4         5.0      Prof          B            40         41.0  Male  141500.0

In [4]:
df=pd.read_csv("salaries.csv")
df.tail(7)

,Unnamed: 0,rank,discipline,yrs.since.phd,yrs.service,sex,salary
396,397.0,Prof,A,31,19.0,Male,150564.0
397,398.0,Prof,A,42,25.0,Male,101738.0
398,399.0,Prof,A,25,15.0,Male,95329.0
399,400.0,AsstProf,A,8,4.0,Male,81035.0
400,NaN,31,26,Male,121200.0,NaN,NaN
401,267.0,Prof,A,31,31.0,Male,126000.0
402,268.0,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
len(df)

403

In [6]:
df.columns

Index(['Unnamed: 0', 'rank', 'discipline', 'yrs.since.phd', 'yrs.service',
       'sex', 'salary'],
      dtype='object')

In [7]:
df.shape

(403, 7)

In [8]:
df.ndim

2

In [9]:
df.index

RangeIndex(start=0, stop=403, step=1)

In [10]:
df.dtypes

Unnamed: 0       float64
rank              object
discipline        object
yrs.since.phd     object
yrs.service      float64
sex               object
salary           float64
dtype: object

In [11]:
df['rank'].value_counts()

rank
Prof         268
AsstProf      67
AssocProf     64
31             1
Name: count, dtype: int64

In [12]:
df['discipline'].value_counts()

discipline
B     219
A     182
26      1
Name: count, dtype: int64

In [13]:
df.describe

<bound method NDFrame.describe of      Unnamed: 0      rank discipline yrs.since.phd  yrs.service   sex  \
0           1.0      Prof          B            19         18.0  Male
1           2.0      Prof          B            20         16.0  Male
2           3.0  AsstProf          B             4          3.0  Male
3           4.0      Prof          B            45         39.0  Male
4           5.0      Prof          B            40         41.0  Male
..          ...       ...        ...           ...          ...   ...
398       399.0      Prof          A            25         15.0  Male
399       400.0  AsstProf          A             8          4.0  Male
400         NaN        31         26          Male     121200.0   NaN
401       267.0      Prof          A            31         31.0  Male
402       268.0       NaN        NaN           NaN          NaN   NaN

       salary
0    139750.0
1    173200.0
2     79750.0
3    115000.0
4    141500.0
..        ...
398   95329.0
399   81035.0
400       NaN
401  126000.0
402       NaN

[403 rows x 7 columns]>

In [14]:
df.describe()

       Unnamed: 0    yrs.service         salary
count  402.000000     401.000000     401.000000
mean   200.833333     319.910224  113722.199501
std    115.422177    6051.568794   30229.134566
min      1.000000       0.000000   57800.000000
25%    101.250000       7.000000   91000.000000
50%    201.500000      16.000000  107300.000000
75%    299.750000      27.000000  134185.000000
max    400.000000  121200.000000  231545.000000

In [15]:
df.describe(include='all')

,Unnamed: 0,rank,discipline,yrs.since.phd,yrs.service,sex,salary
count,402.000000,400,402,401,401.000000,400,401.000000
unique,NaN,4,3,54,NaN,2,NaN
top,NaN,Prof,B,4,NaN,Male,NaN
freq,NaN,268,219,19,NaN,361,NaN
mean,200.833333,NaN,NaN,NaN,319.910224,NaN,113722.199501
std,115.422177,NaN,NaN,NaN,6051.568794,NaN,30229.134566
min,1.000000,NaN,NaN,NaN,0.000000,NaN,57800.000000
25%,101.250000,NaN,NaN,NaN,7.000000,NaN,91000.000000
50%,201.500000,NaN,NaN,NaN,16.000000,NaN,107300.000000
75%,299.750000,NaN,NaN,NaN,27.000000,NaN,134185.000000
max,400.000000,NaN,NaN,NaN,121200.000000,NaN,231545.000000

In [16]:
df['salary'].mean()

np.float64(113722.19950124688)

In [17]:
df.mean(numeric_only=True)

Unnamed: 0        200.833333
yrs.service       319.910224
salary         113722.199501
dtype: float64

In [18]:
df.iloc[0]

Unnamed: 0            1.0
rank                 Prof
discipline              B
yrs.since.phd          19
yrs.service          18.0
sex                  Male
salary           139750.0
Name: 0, dtype: object

In [19]:
df.iloc[101]

Unnamed: 0          102.0
rank                 Prof
discipline              B
yrs.since.phd          30
yrs.service          14.0
sex                  Male
salary           102235.0
Name: 101, dtype: object

In [20]:
df.iloc[[5,9,10]]

,Unnamed: 0,rank,discipline,yrs.since.phd,yrs.service,sex,salary
5,6.0,AssocProf,B,6,6.0,Male,97000.0
9,10.0,Prof,B,18,18.0,Female,129000.0
10,11.0,AssocProf,B,12,8.0,Male,119800.0

### Column Retrieval

###### min,max,mean,median,mode,std,quantile

In [21]:
df['salary'].min()

57800.0

In [22]:
df['salary'].mean().round(1)       #compounding the function

np.float64(113722.2)

In [23]:
df['salary'].quantile(0.25)

np.float64(91000.0)

In [24]:
df['salary'].quantile(0.75)

np.float64(134185.0)

In [25]:
df['salary'].idxmax()

44

In [26]:
df['salary'].mode()

0    92000.0
Name: salary, dtype: float64

In [27]:
df['salary'].value_counts()

salary
92000.0     5
101000.0    4
74000.0     4
72500.0     4
105000.0    3
           ..
168635.0    1
76840.0     1
83001.0     1
113278.0    1
81035.0     1
Name: count, Length: 371, dtype: int64

In [28]:
df['salary_in_lakhs']=df['salary']/100000

In [29]:
df.head()

,Unnamed: 0,rank,discipline,yrs.since.phd,yrs.service,sex,salary,salary_in_lakhs
0,1.0,Prof,B,19,18.0,Male,139750.0,1.3975
1,2.0,Prof,B,20,16.0,Male,173200.0,1.7320
2,3.0,AsstProf,B,4,3.0,Male,79750.0,0.7975
3,4.0,Prof,B,45,39.0,Male,115000.0,1.1500
4,5.0,Prof,B,40,41.0,Male,141500.0,1.4150

#### Duplicate

In [30]:
df.duplicated().sum()

np.int64(1)

In [31]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 403 entries, 0 to 402
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Unnamed: 0       402 non-null    float64
 1   rank             400 non-null    object
 2   discipline       402 non-null    object
 3   yrs.since.phd    401 non-null    object
 4   yrs.service      401 non-null    float64
 5   sex              400 non-null    object
 6   salary           401 non-null    float64
 7   salary_in_lakhs  401 non-null    float64
dtypes: float64(4), object(4)
memory usage: 25.3+ KB

In [32]:
df['rank'].value_counts()

rank
Prof         268
AsstProf      67
AssocProf     64
31             1
Name: count, dtype: int64

In [38]:
mapping={'Prof':3, 'AssocProf':2, 'AsstProf':1}
df['rank']=df['rank'].map(mapping)

In [39]:
df.head()

,Unnamed: 0,rank,discipline,yrs.since.phd,yrs.service,sex,salary,salary_in_lakhs
0,1.0,NaN,B,19,18.0,Male,139750.0,1.3975
1,2.0,NaN,B,20,16.0,Male,173200.0,1.7320
2,3.0,NaN,B,4,3.0,Male,79750.0,0.7975
3,4.0,NaN,B,45,39.0,Male,115000.0,1.1500
4,5.0,NaN,B,40,41.0,Male,141500.0,1.4150

In [41]:
df['discipline']

0        B
1        B
2        B
3        B
4        B
      ...
398      A
399      A
400     26
401      A
402    NaN
Name: discipline, Length: 403, dtype: object

In [42]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
le.fit_transform(df['discipline'])

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 3])

In [43]:
le.classes_

array(['26', 'A', 'B', nan], dtype=object)

In [44]:
df['discipline']=le.inverse_transform(df['discipline'])
df.head()

TypeError: '<' not supported between instances of 'float' and 'str'

NameError: name 'df' is not defined

## One Hot Encoding

In [3]:
import pandas as pd

In [8]:
df=pd.read_csv("salaries.csv")

In [9]:
from sklearn.preprocessing import OneHotEncoder
ohe=OneHotEncoder()
df['sex']=ohe.fit_transform(df['sex']).toarray()

ValueError: Expected a 2-dimensional container but got <class 'pandas.core.series.Series'> instead. Pass a DataFrame containing a single row (i.e. single sample) or a single column (i.e. single feature) instead.